name: CI

on:
  push:
    branches: [master]
    paths:
      - "scripts.js"
      - "common/*"
      - "grammars/*/grammar.js"
      - "grammars/*/src/**"
      - "bindings/**"
      - "binding.gyp"
  pull_request:
    paths:
      - "scripts.js"
      - "common/*"
      - "grammars/*/grammar.js"
      - "grammars/*/src/**"
      - "bindings/**"
      - "binding.gyp"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test-parser:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          test-rust: ${{runner.os == 'Linux'}}
          test-node: true
          test-python: true
          test-go: true
          test-swift: ${{runner.os == 'macOS'}}
      - name: Parse examples
        id: test
        uses: tree-sitter/parse-action@v4
        with:
          files-list: test/files.txt
          invalid-files-list: test/invalid-files.txt
